HospitalManagement/Models/EntityModels/Appointment.cs
namespace HospitalManagement.Models.EntityModels
{
    public class Appointment
    {
        public int Id { get; set; }

        public int? PatientId { get; set; }

        public int? DoctorId { get; set;}

        public string? Fee { get; set; }

        public DateOnly? Date { get; set; }

        public TimeOnly? Time { get; set;}


        public Doctor? Doctor { get; set; }

        public Patient? Patient { get; set; }



    }
}

HospitalManagement/Models/EntityModels/Doctor.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace HospitalManagement.Models.EntityModels
{
    public class Doctor
    {
        public int? Id { get; set; }

        public string? Name { get; set; }

        public string? Fee { get; set; }

        public string? Degree { get; set; }
        public string? PassingInstitute  { get; set; }
        public string? VisitingHour { get; set; }
        public string? RoomNo { get; set; }
        public string? ForAppointment { get; set; }

        public int? DoctorDepartmentId { get; set; }


        [ValidateNever]
        public DoctorDepartment? DoctorDepartment { get; set; } //Optional Navigation Property

        public IEnumerable<Appointment> Appointments { get; set; } = new List<Appointment>();
    }
}

HospitalManagement/Models/EntityModels/Patient.cs
namespace HospitalManagement.Models.EntityModels
{
    public class Patient
    {
        public int Id { get; set; }

        public string? Name { get; set; }

        public DateOnly? Dob { get; set; }

        public string? Mobile { get; set; }

        public string? Gender { get; set; }

        public string? Profession { get; set; }

        public string? Weight { get; set; }


        public IEnumerable<Appointment> Appointments { get; set; } = new List<Appointment>();


    }
}

HospitalManagement/Controllers/AppointmentController.cs
using HospitalManagement.Data;
using HospitalManagement.Models.EntityModels;
using HospitalManagement.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace HospitalManagement.Controllers
{
    public class AppointmentController : Controller
    {
        public readonly _DbContext _context;

        public AppointmentController(_DbContext context)
        {
            _context = context;
        }

        //public IActionResult Index()
        //{
        //    var appointments = _context.Appointments;
            
        //    return Ok(appointments);
        //}


        public IActionResult Index(int page = 1, int pageSize = 5, string search = "")
        {
            var appointments = _context.Appointments.Include(u => u.Patient).Include(d =>d.Doctor);


            Pagination p = new Pagination(appointments.Count(), page, pageSize);
            ViewBag.Pagination = p;
            var result = appointments.Skip(p.Skip).Take(pageSize).ToList<Appointment>();

            return View(result);
        }



        [ActionName("Create")]

        public IActionResult Save(int id)
        {
            var app = _context.Appointments.Find(id);
            var p = _context.Patients;
            ViewBag.Patients = p;

            var d = _context.Doctors;
            ViewBag.Doctors = d;
            return View(app);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Save([Bind("PatientId", "DoctorId", "Fee", "Date", "Time")] Appointment appointment)
        {
            _context.Appointments.Add(appointment);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }




        public IActionResult Details(int id)
        {
            var a = _context.Appointments.Include(u => u.Doctor).Include(p => p.Patient).Where(a => a.Id == id).FirstOrDefault();
            return View(a);
        }

        public IActionResult Edit(int id)
        {


            var app = _context.Appointments.Find(id);
            var p = _context.Patients;
            ViewBag.Patients = p;

            var d = _context.Doctors;
            ViewBag.Doctors = d;

            return View(app);
        }


        [HttpPost]
        public IActionResult Edit(int Id, [Bind("Id", "PatientId", "DoctorId", "Fee", "Date", "Time")] Appointment appointment)
        {
            if (Id != appointment.Id)
            {
                return NotFound();
            }
            _context.Update(appointment);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }



        [ActionName("Delete")]
        public IActionResult ConfirmDelete(int id)
        {

            var a = _context.Appointments.Where(a => a.Id == id).SingleOrDefault();
            //FirstOrDefault


            return View(a);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var appointment = _context.Appointments.Find(id);
            _context.Remove(appointment);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));

        }


    }
}

HospitalManagement/Controllers/DoctorController.cs
using HospitalManagement.Data;
using HospitalManagement.Models.EntityModels;
using HospitalManagement.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using System.Linq;
using System.Net;

namespace HospitalManagement.Controllers
{
    public class DoctorController : Controller
    {
        public readonly _DbContext _context;

        public DoctorController(_DbContext context)
        {
            _context = context;

        }
        //public IActionResult Index()
        //{
        //    var doctors = _context.Doctors.Include(u => u.DoctorDepartment);
        //    return Ok(doctors);
        //}


        public IActionResult Index(int page = 1, int pageSize = 5, string search = "")
        {
            var doctors = _context.Doctors.Include(u=> u.DoctorDepartment);

            Pagination p = new Pagination(doctors.Count(), page, pageSize);
            ViewBag.Pagination = p;
            var result = doctors.Skip(p.Skip).Take(pageSize).ToList<Doctor>();

            return View(result);
        }


        [ActionName("Create")]

        public IActionResult Save()
        {
            return View(_context.DoctorDepartments);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Save([Bind("Name", "Fee", "Degree", "PassingInstitute", "VisitingHour", "RoomNo", "ForAppointment", "DoctorDepartmentId")] Doctor doctor)
        {
            _context.Doctors.Add(doctor);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            var u = _context.Doctors/*.Include(u => u.DoctorDepartment)*/.Where(u => u.Id == id).FirstOrDefault();
            return View(u);
        }

        public IActionResult Edit(int id)
        {

            var doc = _context.Doctors.Find(id);
            var dd = _context.DoctorDepartments;
            ViewBag.DoctorDepartments = dd;

            return View(doc);
        }

        [HttpPost]
        public IActionResult Edit(int Id, [Bind("Id","Name","Degree","Fee", "PassingInstitute", "VisitingHour", "RoomNo", "ForAppointment", "DoctorDepartmentId")] Doctor doctor)
        {
            if(Id != doctor.Id)
            {
                return NotFound();
            }
            _context.Update(doctor);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }


        [ActionName("Delete")]
        public IActionResult ConfirmDelete(int id)
        {
            
            var u = _context.Doctors.Where(u => u.Id == id).SingleOrDefault();
            //FirstOrDefault


            return View(u);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var doctor = _context.Doctors.Find(id);
            _context.Remove(doctor);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));

        }
    }
}

HospitalManagement/Controllers/PatientController.cs
using HospitalManagement.Data;
using HospitalManagement.Models.EntityModels;
using HospitalManagement.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace HospitalManagement.Controllers
{
    public class PatientController : Controller
    {

        public readonly _DbContext _context;

        public PatientController(_DbContext context)
        {
            _context = context;

        }
        //public IActionResult Index()
        //{
        //    var patients = _context.Patients.Include(u => u.Doctor);
        //    return View(patients);
        //}


        public IActionResult Index(int page = 1, int pageSize = 5, string search = "")
        {
            var patients = _context.Patients;

            Pagination p = new Pagination(patients.Count(), page, pageSize);
            ViewBag.Pagination = p;
            var result = patients.Skip(p.Skip).Take(pageSize).ToList<Patient>();

            return View(result);
        }



        [ActionName("Create")]

        public IActionResult Save()
        {
            return View(_context.Doctors);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Save([Bind("Name", "Dob", "Mobile", "Gender", "Profession", "Weight")] Patient patient)
        {
            _context.Patients.Add(patient);
            
            _context.SaveChanges();

            return RedirectToAction("Index");
        }


        public IActionResult Details(int id)
        {
            var p = _context.Patients.Where(p => p.Id == id).FirstOrDefault();
            return View(p);
        }


        public IActionResult Edit(int id)
        {

            var p = _context.Patients.Find(id);          

            return View(p);
        }

        [HttpPost]
        public IActionResult Edit(int Id, [Bind("Id", "Name", "Dob", "Mobile", "Gender", "Profession", "Weight")] Patient patient)
        {
            if (Id != patient.Id)
            {
                return NotFound();
            }
            _context.Update(patient);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [ActionName("Delete")]
        public IActionResult ConfirmDelete(int id)
        {

            var p = _context.Patients.Where(p => p.Id == id).SingleOrDefault();
            
            return View(p);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var patient = _context.Patients.Find(id);
            _context.Remove(patient);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));

        }
    }

}

HospitalManagement/Controllers/RoleController.cs
using HospitalManagement.Data;
using HospitalManagement.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using HospitalManagement.Models.EntityModels;

namespace HospitalManagement.Controllers
{
    public class RoleController : Controller
    {
        public readonly _DbContext _context;

        public RoleController(_DbContext context)
        {
            _context = context;
        }

        public IActionResult Index(int page=1,int pageSize=5,string search="" )
        {
            var roles = _context.Roles;

            Pagination p=new Pagination(roles.Count(),page, pageSize);
            ViewBag.Pagination = p;
            var result=roles.Skip(p.Skip).Take(pageSize).ToList<Role>();

            return View(result);
        }


        [ActionName("Create")]
        public IActionResult Save()
        {
            return View(_context.Roles);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Save([Bind( "Name")] Role role)
        {

            
            _context.Roles.Add(role);
            
            _context.SaveChanges();

            return RedirectToAction("Index");
        }


        public IActionResult Details(int id)
        {
            var u = _context.Roles.Include(u => u.Users).Where(u => u.Id == id).FirstOrDefault();
            return View(u);
        }


        public IActionResult Edit(int id)
        {
            
            var role = _context.Roles.Find(id);
            
            return View(role);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int Id, [Bind("Id", "Name")] Role role)
        {

            if (Id != role.Id)
            {
                return NotFound();
            }

            _context.Update(role);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }


        [ActionName("Delete")]
        public IActionResult ConfirmDelete(int id)
        {
            //var u = _context.Roles.Include(u => u.Users).Where(u => u.Id == id).SingleOrDefault<Role>();
            var u = _context.Roles.Where(u => u.Id == id).SingleOrDefault();
            //FirstOrDefault
            

            return View(u);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var role = _context.Roles.Find(id);
            _context.Remove(role);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));

        }
    }
}

HospitalManagement/Controllers/UserController.cs
using HospitalManagement.Data;
using HospitalManagement.Models.EntityModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using HospitalManagement.Models.ViewModels;
using System.Linq;

namespace HospitalManagement.Controllers
{
    public class UserController : Controller
    {
        public readonly _DbContext _context;
        public IWebHostEnvironment _host;

        public UserController(_DbContext context, IWebHostEnvironment host)
        {
            this._context = context;
            _host = host;
        }

        

        //Include Method


        // public async Task<IActionResult>Index()
        // {
        //     var a = _context.Roles.ToList();
        //     var b= _context.Users.ToList(); 
        //     return Ok(b); 
        // }


        public async Task<IActionResult> Index(int page = 1, int pageSize = 4, string search = "")
        {
            var stopwatch = Stopwatch.StartNew();
            stopwatch.Start();



            var Result = _context.Users.Join(_context.Roles, u => u.RoleId, r => r.Id, (u, r) => new UserReport { Id = u.Id, Name = u.Name, Role = r.Name }).Where(p => p.Name.Contains(search));

            Pagination p = new Pagination(Result.Count(), page, pageSize);
            ViewBag.Pagination = p;

            var users = await Result.Skip(p.Skip).Take(pageSize).ToListAsync<UserReport>();


            stopwatch.Stop();
            long ms = stopwatch.ElapsedMilliseconds;
            ViewBag.ms = ms;

            return View(users);
        }






        [ActionName("Create")]
        public IActionResult Save()
        {
            return View(_context.Roles);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Save([Bind("Name", "Password", "RoleId", "Email", "FullName", "ContactNo", "File")] User user)
        {

            _context.Users.Add(user);
            Upload(user.File, user.Name);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            var u = _context.Users.Include(u => u.Role).Where(u => u.Id == id).FirstOrDefault();
            return View(u);
        }


        public IActionResult Edit(int id)
        {
            var u = _context.Users.Find(id);
            var r = _context.Roles;
            ViewBag.Roles = r;
            return View(u);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int Id, [Bind("Id", "Name", "Password", "RoleId", "Email", "FullName", "ContactNo", "File")] User user)
        {
            if (Id != user.Id)
            {
                return NotFound();
            }

            if (user.File != null)
            {
                user.Photo = user.Name + Path.GetExtension(user.File.FileName);
            }

            _context.Users.Update(user);
            _context.SaveChanges();

            //Photo Upload
            Upload(user.File, user.Name);

            return RedirectToAction(nameof(Index));
        }

        public void Upload(IFormFile file, String name)
        {
            if (file != null)
            {
                String ext = Path.GetExtension(file.FileName);
                using (FileStream fs = System.IO.File.Create($"{_host.ContentRootPath}/wwwroot/img/{name}{ext}"))
                {
                    file.CopyTo(fs);
                    fs.Flush();
                }
            }
        }

        [ActionName("Delete")]
        public IActionResult ConfirmDelete(int id)
        {
            var u = _context.Users.Include(u => u.Role).Where(u => u.Id == id).SingleOrDefault<User>();

            return View(u);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var user = _context.Users.Find(id);
            _context.Users.Remove(user);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));

        }
    }
}

HospitalManagement/Views/Shared/Layout/Menus/_Account&Finance.cshtml
<li class="nav-item ">
    <a href="#" class="nav-link ">
        
        <i class="nav-icon fas fa-file-invoice"></i>
        <p>
            Accounts & Finance
            <i class="right fas fa-angle-left"></i>
        </p>
    </a>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="./index.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Dashboard</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="./index2.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Debit Voucher(Expense)</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="./index3.html" class="nav-link ">
                <i class="far fa-circle nav-icon"></i>
                <p>Credit Voucher(Income)</p>
            </a>
        </li>

        <li class="nav-item">
            <a href="./index3.html" class="nav-link ">
                <i class="far fa-circle nav-icon"></i>
                <p>Advance Payment</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="./index3.html" class="nav-link ">
                <i class="far fa-circle nav-icon"></i>
                <p>Installment</p>
            </a>
        </li>

        <li class="nav-item">
            <a href="./index3.html" class="nav-link ">
                <i class="far fa-circle nav-icon"></i>
                <p>Petty Cash</p>
            </a>
        </li>

        <li class="nav-item">
            <a href="./index3.html" class="nav-link ">
                <i class="far fa-circle nav-icon"></i>
                <p>Fund Management</p>
            </a>
        </li>

        <li class="nav-item">
            <a href="./index3.html" class="nav-link ">
                <i class="far fa-circle nav-icon"></i>
                <p>Vendor/Supplier</p>
            </a>
        </li>

        <li class="nav-item">
            <a href="./index3.html" class="nav-link ">
                <i class="far fa-circle nav-icon"></i>
                <p>Accounts Configaration</p>
            </a>
        </li>

        <li class="nav-item">
            <a href="./index3.html" class="nav-link ">
                <i class="far fa-circle nav-icon"></i>
                <p>Salary</p>
            </a>
        </li>
    </ul>
</li>

HospitalManagement/Views/Shared/Layout/Menus/_Appointment.cshtml
<li class="nav-item ">
    <a href="#" class="nav-link ">
        
        <i class="nav-icon fas fa-calendar-check"></i>
        <p>
            Appointment
            <i class="right fas fa-angle-left"></i>
        </p>
    </a>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a asp-controller="Patient" asp-action="Index" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Patient</p>
            </a>
        </li>
        <li class="nav-item">
            <a asp-controller="Appointment" asp-action="Index" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Appointment</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="./index3.html" class="nav-link ">
                <i class="far fa-circle nav-icon"></i>
                <p>Upcoming Appointment</p>
            </a>
        </li>
    </ul>
</li>

HospitalManagement/Views/Shared/Layout/Menus/_Dashboard.cshtml
<li class="nav-item ">
    <a href="#" class="nav-link ">
        <i class="nav-icon fas fa-tachometer-alt"></i>
        <p>
            Dashboard
            <i class="right fas fa-angle-left"></i>
        </p>
    </a>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="./index.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Dashboard v1</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="./index2.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Dashboard v2</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="./index3.html" class="nav-link ">
                <i class="far fa-circle nav-icon"></i>
                <p>Dashboard v3</p>
            </a>
        </li>
    </ul>
</li>

HospitalManagement/Views/Shared/Layout/Menus/_Doctors.cshtml
<li class="nav-item ">
    <a href="#" class="nav-link ">
        
        <i class="nav-icon fas fa-user-md"></i>
        <p>
            Doctors
            <i class="right fas fa-angle-left"></i>
        </p>
    </a>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a asp-controller="Doctor" asp-action="Index" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>List of Doctors</p>
            </a>
        </li>

        <li class="nav-item">
            <a asp-controller="DoctorDepartment" asp-action="Index" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Doctor Department</p>
            </a>
        </li>

        <li class="nav-item">
            <a href="./index2.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Treatment History</p>
            </a>
        </li>

        <li class="nav-item">
            <a href="./index2.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Doctors Holiday</p>
            </a>
        </li>
        
    </ul>
</li>

HospitalManagement/Views/Shared/Layout/Menus/_Hrm.cshtml
<li class="nav-item ">
    <a href="#" class="nav-link ">
        
        <i class="nav-icon fas fa-users"></i>
        <p>
            HRM
            <i class="right fas fa-angle-left"></i>
        </p>
    </a>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="./index.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Employee Management</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="./index2.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Payroll</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="./index3.html" class="nav-link ">
                <i class="far fa-circle nav-icon"></i>
                <p>Attendance</p>
            </a>
        </li>
    </ul>
</li>

HospitalManagement/Views/Shared/Layout/Menus/_LabManagement.cshtml
<li class="nav-item ">
    <a href="#" class="nav-link ">
        
        <i class="nav-icon fas fa-flask"></i>
        <p>
            Lab Management
            <i class="right fas fa-angle-left"></i>
        </p>
    </a>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="./index.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Collect Sample</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="./index2.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Pending Sample Collect</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="./index3.html" class="nav-link ">
                <i class="far fa-circle nav-icon"></i>
                <p>Complete Report</p>
            </a>
        </li>
    </ul>
</li>

HospitalManagement/Views/Shared/Layout/Menus/_MedicalServices.cshtml
<li class="nav-item ">
    <a href="#" class="nav-link ">
        
        <i class="nav-icon fas fa-hand-holding-medical"></i>
        <p>
            Medical Services
            <i class="right fas fa-angle-left"></i>
        </p>
    </a>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="./index.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Medical Services Sales</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="./index2.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Due Receive</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="./index3.html" class="nav-link ">
                <i class="far fa-circle nav-icon"></i>
                <p>Deliver Reports</p>
            </a>
        </li>
    </ul>
</li>

HospitalManagement/Views/Shared/Layout/Menus/_Patient.cshtml
<li class="nav-item ">
    <a href="#" class="nav-link ">
        
        <i class="nav-icon fas fa-user-injured"></i>
        <p>
            Patient
            <i class="right fas fa-angle-left"></i>
        </p>
    </a>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="./index.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>New Admission</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="./index2.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Admitted Patients</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="./index3.html" class="nav-link ">
                <i class="far fa-circle nav-icon"></i>
                <p>Release Patients</p>
            </a>
        </li>

        <li class="nav-item">
            <a href="./index3.html" class="nav-link ">
                <i class="far fa-circle nav-icon"></i>
                <p>All Patients List</p>
            </a>
        </li>

        <li class="nav-item">
            <a href="./index3.html" class="nav-link ">
                <i class="far fa-circle nav-icon"></i>
                <p>Due Collection</p>
            </a>
        </li>
    </ul>
</li>

HospitalManagement/Views/Shared/Layout/Menus/_PharmacyManagement.cshtml
<li class="nav-item ">
    <a href="#" class="nav-link ">
        
        <i class="nav-icon fas fa-pills"></i>
        <p>
            Pharmacy Management
            <i class="right fas fa-angle-left"></i>
        </p>
    </a>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="./index.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Sales</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="./index2.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Purchase</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="./index3.html" class="nav-link ">
                <i class="far fa-circle nav-icon"></i>
                <p>Inventory</p>
            </a>
        </li>
    </ul>
</li>

HospitalManagement/Views/Shared/Layout/Menus/_Settings.cshtml
<li class="nav-item ">
    <a href="#" class="nav-link ">
        
        <i class="nav-icon fas fa-cogs"></i>
        <p>
            Setting
            <i class="right fas fa-angle-left"></i>
        </p>
    </a>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a asp-controller="Role" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Manage Role</p>
            </a>
        </li>
        <li class="nav-item">
            <a asp-controller="User" asp-action="Index" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Manage User</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="./index3.html" class="nav-link ">
                <i class="far fa-circle nav-icon"></i>
                <p>Change Password</p>
            </a>
        </li>

        <li class="nav-item">
            <a href="./index3.html" class="nav-link ">
                <i class="far fa-circle nav-icon"></i>
                <p>System Log Activity</p>
            </a>
        </li>

    </ul>
</li>

HospitalManagement/Views/Shared/Layout/Menus/_System.cshtml
<li class="nav-item ">
    <a href="#" class="nav-link ">

        <i class="nav-icon fas fa-users"></i>
        <p>
            System
            <i class="right fas fa-angle-left"></i>
        </p>
    </a>
    <ul class="nav nav-treeview">
        <li class="nav-item">
            <a href="./index.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Manage Role</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="./index2.html" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Manage User</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="./index3.html" class="nav-link ">
                <i class="far fa-circle nav-icon"></i>
                <p>Change Password</p>
            </a>
        </li>

        <li class="nav-item">
            <a href="./index3.html" class="nav-link ">
                <i class="far fa-circle nav-icon"></i>
                <p>System Log Activity</p>
            </a>
        </li>

    </ul>
</li>