HospitalManagement/Models/EntityModels/DoctorDepartment.cs
namespace HospitalManagement.Models.EntityModels
{
    public class DoctorDepartment
    {
        public int? Id { get; set; }

        public string? Name { get; set; }

        public IEnumerable<Doctor> Doctors { get; set; } = new List<Doctor>();//Navigation Property
    }
}

HospitalManagement/Controllers/DoctorDepartmentController.cs
using HospitalManagement.Data;
using HospitalManagement.Models.EntityModels;
using HospitalManagement.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace HospitalManagement.Controllers
{
    public class DoctorDepartmentController : Controller
    {
        public readonly _DbContext _context;

        public DoctorDepartmentController(_DbContext context)
        {
            _context = context;
        }
        public IActionResult Index(int page = 1, int pageSize = 5, string search = "")
        {
            var doctordepartments = _context.DoctorDepartments;

            Pagination p = new Pagination(doctordepartments.Count(), page, pageSize);
            ViewBag.Pagination = p;
            var result = doctordepartments.Skip(p.Skip).Take(pageSize).ToList<DoctorDepartment>();

            return View(result);
        }


        [ActionName("Create")]
        public IActionResult Save()
        {
            return View(_context.DoctorDepartments);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Save([Bind("Name")] DoctorDepartment doctordepartment)
        {


            _context.DoctorDepartments.Add(doctordepartment);

            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            var u = _context.DoctorDepartments.Include(u => u.Doctors).Where(u => u.Id == id).FirstOrDefault();
            return View(u);
        }

        public IActionResult Edit(int id)
        {

            var dd = _context.DoctorDepartments.Find(id);

            return View(dd);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int Id, [Bind("Id", "Name")] DoctorDepartment doctordepartment)
        {

            if (Id != doctordepartment.Id)
            {
                return NotFound();
            }

            _context.Update(doctordepartment);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }


        [ActionName("Delete")]
        public IActionResult ConfirmDelete(int id)
        {
            
            var u = _context.DoctorDepartments.Where(u => u.Id == id).SingleOrDefault();
            


            return View(u);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var doctordepartment = _context.DoctorDepartments.Find(id);
            _context.Remove(doctordepartment);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));

        }
    }
}

HospitalManagement/Views/DoctorDepartment/Create.cshtml
@using HospitalManagement.Models.ViewModels


   @{
       PageHeader ph = new PageHeader() { Title = "Create Contents" };
}
<partial name="../Shared/Widgets/_PageHeader.cshtml" model="ph" />






<section class="content">

    <!-- Default box -->
    <div class="card">
        <partial name="../Shared/Widgets/_CardHeader.cshtml" />
        <div class="card-body">

            @* <div class="card"> *@

                <!-- /.card-header -->
                <div class="card-body p-0">

<div class="card card-info">
    <div class="card-header">
        <h3 class="card-title">Create Contents</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
                    <form class="form-horizontal" asp-controller="DoctorDepartment" asp-action="Save">
        <div class="card-body">


                     <div class="form-group row">

                                <label for="DoctorDepartmentId" class="col-sm-2 col-form-label">DoctorDepartment</label>

                           <div class="col-sm-10">
                                    <select class="form-control" name="DoctorDepartmentId">
                                        @foreach (var doctordepartment in Model)
                                    {
                                            <option value="@doctordepartment.Id">@doctordepartment.Name</option>
                                     }
                                </select>
                           </div>

                     </div>



            
            <div class="form-group row">
                <label for="name" class="col-sm-2 col-form-label">Name</label>
                <div class="col-sm-10">
                    <input type="text" name="Name" class="form-control" id="Name" placeholder="Name">
                </div>
            </div>


        
                           

            

        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <button type="submit" class="btn btn-info">Sign in</button>
            <button type="reset" class="btn btn-default float-right">Clear</button>
        </div>
        <!-- /.card-footer -->
    </form>
</div>

                </div>
                <!-- /.card-body -->
            @* </div> *@

         </div> 
        <!-- /.card-body -->
        <div class="card-footer">
            Footer
        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>

HospitalManagement/Views/DoctorDepartment/Delete.cshtml
@using HospitalManagement.Models.EntityModels
@model DoctorDepartment

<div>
    Dr.Name: @Model.Name<br />
    
</div>

<form asp-action="Delete" method="post">
    <input type="hidden" asp-route-id="@Model.Id" />
    <input type="submit" class="btn btn-danger" value="Are you sure?" />
</form>

HospitalManagement/Views/DoctorDepartment/Details.cshtml
@using HospitalManagement.Models.EntityModels
@using HospitalManagement.Models.ViewModels

@{
    PageHeader ph = new PageHeader() { Title = "Details" };
}
<partial name="../Shared/Widgets/_PageHeader.cshtml" model="ph" />



<!-- Default box -->
<div class="card">
    <div class="card-header">
        <h3 class="card-title">
            <a asp-controller="DoctorDepartment" class="btn btn-success" asp-action="Index">New Contents</a>
        </h3>

        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                <i class="fas fa-times"></i>
            </button>
        </div>
    </div>
    <div class="card-body">

        

                <table class="table table-striped">
                    <tr><th colspan="2">User Info</th></tr>
                    <tr><th>ID</th><td>@Model.Id</td></tr>
                    <tr><th>Name</th><td>@Model.Name</td></tr>
                    
                </table>

            


    </div>
    <!-- /.card-body -->
    <div class="card-footer">
        Footer 
    </div>
    <!-- /.card-footer-->
</div>
<!-- /.card -->

HospitalManagement/Views/DoctorDepartment/Edit.cshtml
@using HospitalManagement.Models.EntityModels
@model DoctorDepartment
@using HospitalManagement.Models.ViewModels

@{
    PageHeader ph = new PageHeader() { Title = "Edit Doctor Department" };
}
<partial name="../Shared/Widgets/_PageHeader.cshtml" model="ph" />


<section class="content">
    <!-- Default box -->
    <div class="card">
        <partial name="../Shared/Widgets/_CardHeader.cshtml" />

        <div class="card-body">

            <form class="form-horizontal" asp-action="Edit" asp-controller="DoctorDepartment">

                

                <div class="form-group row">
                    <label for="Id" class="col-sm-2 col-form-label">Id</label>
                    <div class="col-sm-10">
                        <input type="number" class="form-control" asp-for="Id" />
                    </div>
                </div>

                <div class="form-group row">
                    <label for="name" class="col-sm-2 col-form-label">Name</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" asp-for="Name" />
                    </div>

                </div>

               

                <div class="card-footer">
                    <input class="btn btn-info" type="submit" value="Submit" name="Submit" />
                </div>
            </form>

        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>

HospitalManagement/Views/DoctorDepartment/Index.cshtml
@using HospitalManagement.Models.EntityModels
@using HospitalManagement.Models.ViewModels
@model IEnumerable<DoctorDepartment>



@{
    PageHeader ph = new PageHeader() { Title = "Manage Doctor Department" };
}
<partial name="../Shared/Widgets/_PageHeader.cshtml" model="ph" />


<section class="content">
<!-- Default box -->
<div class="card">
    <div class="card-header">
        <h3 class="card-title">
                <a asp-controller="DoctorDepartment" class="btn btn-success" asp-action="Create">New Contents</a>
        </h3>

        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                <i class="fas fa-times"></i>
            </button>
        </div>
    </div>
    <div class="card-body">

        <div class="card">

            <!-- /.card-header -->
            <div class="card-body p-0">

                <table class="table table-striped">
                    <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Action</th>
                                </tr>
                    </thead>


                        @foreach (DoctorDepartment dd in Model)
                {
                            <tr>
                                <td>@dd.Id</td>
                                <td>@dd.Name</td>
                                <td>
                                    <div class="btn-group">
                                        <a asp-controller="DoctorDepartment" asp-action="Details" asp-route-id="@dd.Id" class="btn btn-success btn-sm">
                                            <i class="far fa-file-alt"></i>
                                        </a>
                                        <a asp-controller="DoctorDepartment" asp-action="Edit" asp-route-id="@dd.Id" class="btn btn-warning btn-sm">
                                            <i class="fas fa-pencil-alt"></i>
                                        </a>
                                        <a asp-controller="DoctorDepartment" asp-action="Delete" asp-route-id="@dd.Id" class="btn btn-danger btn-sm">
                                            <i class="fas fa-trash-alt"></i>
                                        </a>
                                    </div>
                                </td>
                                </tr>
                }

                </table>
                    <partial name="../Shared/Widgets/_Pagination.cshtml" />
            </div>
            <!-- /.card-body -->
        </div>
       

    </div>
    <!-- /.card-body -->
    <div class="card-footer">
        Footer 
    </div>
    <!-- /.card-footer-->
</div>
<!-- /.card -->
</section>